<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var Login $block */

use Magento\Customer\Block\Form\Login;

?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              method="post"
              id="question-form"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field title required">
                    <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name" value="" type="text"
                               id="name" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Name')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="email">
                        <input name="email" value=""
                               id="email" type="text" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="message"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                    <div class="message">
                        <input name="message" value=""
                               id="message" type="text" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Message')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
                    <div class="company">
                        <input name="company" value=""
                               id="company" type="text" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Company')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="rating"><span><?= $block->escapeHtml(__('Rating')) ?></span></label>
                    <div class="rating">
                        <input name="rating" value=""
                               id="rating" type="number" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Rating')) ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="status"><span><?= $block->escapeHtml(__('Status')) ?></span></label>
                    <select name="status" id="status">
                        <option value="0">Disable</option>
                        <option value="1">Enable</option>
                    </select>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action login primary" name="send" id="submit">
                            <span><?= $block->escapeHtml(__('Save')) ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'mage/storage', 'mage/url'], function ($, storage, urlBuilder) {
        $('#submit').on('click', function () {
            var formData = new FormData($("#question-form")[0]);
            formData = JSON.stringify(Object.fromEntries(formData));
            storage.post(
                urlBuilder.build("rest/V1/testimonial/save"),
                JSON.stringify({data: formData})
            ).done(function (r) {
                alert("Create Testimonial Success");
            }).fail(function (r) {
                alert("Error");
            });
        });
    });
</script>
