<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2022 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * @var Tigren\Testimonial\Block\Storefront\Edit $block
 */

use Magento\Customer\Block\Form\Login;

$data = $block->getEditData();
?>
<?php

/** @var Login $block */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $this->getUrl("testimonial/storefront/update") ?>.?id=<?= $data['entity_id'] ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field title required">
                    <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                    <div class="control">
                        <input name="name" value="<?= $data['name'] ?>" type="text"
                               id="name" class="input-text"
                               title="<?= $data['name'] ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="email" value="<?= $data['email'] ?>"
                               id="email" type="text" class="input-text"
                               title="<?= $data['email'] ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="message"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                    <div class="control">
                        <input name="message" value="<?= $data['message'] ?>"
                               id="message" type="text" class="input-text"
                               title="<?= $data['message'] ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="Company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
                    <div class="control">
                        <input name="company" value="<?= $data['company'] ?>"
                               id="company" type="text" class="input-text"
                               title="<?= $data['company'] ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="rating"><span><?= $block->escapeHtml(__('Rating')) ?></span></label>
                    <div class="control">
                        <input name="rating" value="<?= $data['rating'] ?>"
                               id="rating" type="text" class="input-text"
                               title="<?= $data['rating'] ?>">
                    </div>
                </div>
                <div class="field content required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Status')) ?></span></label>
                    <div class="control">
                        <select name="status" id="status">
                            <option
                                value="<?= $data['status'] ?>"><?php echo (1 == $data['status']) ? 'Enable' : 'Disable'; ?></option>
                            <option value="0">Disable</option>
                            <option value="1">Enable</option>
                        </select>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?= $block->escapeHtml(__('Save')) ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
